properties([
  disableConcurrentBuilds(),
  buildDiscarder(logRotator(numToKeepStr: '10', daysToKeepStr: '30'))
])

timeout(time: 1, unit: 'HOURS') {
  parallel cpu: {
      buildPod(context: 'example') {
        sh 'nproc'
        sh 'g++ -v'
        sh 'pip3 -V'
      }
  },
  cuda: {
    buildPod(context: 'example', dockerfile: 'Dockerfile-cuda', tag: 'cuda', gpus: 1) {
      sh 'nproc'
      sh 'nvidia-smi'
    }
  }
}
/* declarative:
pipeline {
  agent none
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
    timeout(time: 1, unit: 'HOURS')
  }
  stages {
    stage('main') {
      parallel {
        stage('cpu') {
          steps {
            buildPod(context: 'example') {
              sh 'nproc'
              sh 'g++ -v'
              sh 'pip3 -V'
            }
          }
        }
        stage('cuda') {
          steps {
            buildPod(context: 'example', dockerfile: 'Dockerfile-cuda', tag: 'cuda', gpus: 1) {
              sh 'nproc'
              sh 'nvidia-smi'
            }
          }
        }
      }
    }
  }
} */
