pipeline {
  agent none
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
    timeout(time: 1, unit: 'HOURS')
  }
  environment {
    IMAGE = "$REGISTRY_PREFIX/${JOB_NAME.toLowerCase()}:$BUILD_NUMBER"
  }
  stages {
    stage('image') {
      agent {
        kubernetes {
          inheritFrom 'podman'
          defaultContainer 'main'
        }
      }
      steps {
        sh 'podman build -t $IMAGE jenkins'
        sh 'podman push $IMAGE'
      }
    }
    stage('build') {
      agent {
        kubernetes {
	  containerTemplate {
	    name 'main'
	    image IMAGE
	  }
          defaultContainer 'main'
        }
      }
      steps {
        sh 'g++ -v'
        sh 'python -V'
      }
    }
  }
}
